# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VC2qWgVzPMpUhN7fkCPslxW_uRH1b1Qh
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression

pd.options.display.float_format = '{:,.2f}'.format

from pandas.plotting import register_matplotlib_converters
register_matplotlib_converters()

data = pd.read_csv('cost_revenue_dirty.csv')

data.sample(5)

data.duplicated().values.any()

data.info()

data['USD_Production_Budget'] = data['USD_Production_Budget'].str.replace("$", "", regex=True).str.replace(",", "", regex=True)
data['USD_Production_Budget'] = pd.to_numeric(data['USD_Production_Budget'])

data.sample(1)

data['USD_Worldwide_Gross'] = data['USD_Worldwide_Gross'].str.replace("$", "", regex=True).str.replace(",", "", regex=True)
data['USD_Worldwide_Gross'] = pd.to_numeric(data['USD_Worldwide_Gross'])

data['USD_Domestic_Gross'] = data['USD_Domestic_Gross'].str.replace("$", "", regex=True).str.replace(",", "", regex=True)
data['USD_Domestic_Gross'] = pd.to_numeric(data['USD_Domestic_Gross'])

data.info()

data['Release_Date'] = pd.to_datetime(data['Release_Date'])

data.info()

data['USD_Domestic_Gross'].min()

data['USD_Production_Budget'].idxmax()

data.loc[3529].USD_Worldwide_Gross

data['USD_Production_Budget'].idxmin()

data.loc[2427].USD_Worldwide_Gross

data.sample(5)

len(data[data['USD_Domestic_Gross'] == 0])

highest_budget = data[data['USD_Domestic_Gross'] == 0]

highest_budget.sort_values(by = "USD_Production_Budget", ascending=False).head(5)

len(data[data['USD_Worldwide_Gross'] == 0])

highest_budget = data[data['USD_Worldwide_Gross'] == 0]

highest_budget.sort_values(by = "USD_Production_Budget", ascending=False).head(5)

international_releases = data.query('USD_Worldwide_Gross != 0 and USD_Domestic_Gross == 0')

international_releases

data.sample(1)

data_clean = data[data['Release_Date'] < "2018-05-1"]

data_clean

plt.figure(figsize=(8, 4), dpi=200)
sns.scatterplot(
    data=data_clean, 
    x='USD_Production_Budget', 
    y='USD_Worldwide_Gross'
)

plt.show()

plt.figure(figsize=(8,4), dpi=200)
 
# set styling on a single chart
with sns.axes_style('darkgrid'):
  ax = sns.scatterplot(data=data_clean,
                       x='USD_Production_Budget', 
                       y='USD_Worldwide_Gross',
                       hue='USD_Worldwide_Gross',
                       size='USD_Worldwide_Gross')
 
  ax.set(ylim=(0, 3000000000),
        xlim=(0, 450000000),
        ylabel='Revenue in $ billions',
        xlabel='Budget in $100 millions')

plt.figure(figsize=(8, 4), dpi=200)
with sns.axes_style("dark"):
  ax = sns.scatterplot(
      data=data_clean, 
      x='Release_Date',
      y='USD_Production_Budget', 
      hue='USD_Worldwide_Gross', 
      size='USD_Worldwide_Gross'
  )
  ax.set(ylim=(0, data_clean.USD_Production_Budget.max()),
         xlim=(data_clean.Release_Date.min(), data_clean.Release_Date.max()),
         ylabel="Budget in $100 millions",
         xlabel="Year")
plt.show()

data_clean.sample(3)

from pandas.core.indexes.period import DatetimeIndex
all_years = DatetimeIndex(data=data_clean.Release_Date, dtype='datetime64[ns]').year

converted_years = (all_years//10)*10

data_clean.insert(6, "Decade", converted_years)

data_clean.sample(5)

old_films = data_clean[data_clean.Decade < 1970]
new_films = data_clean[data_clean.Decade >= 1970]

len(old_films)

len(new_films)

5231+153

old_films.sort_values(by='USD_Production_Budget', ascending=False)

sns.regplot(
    data=data_clean,
    x="USD_Production_Budget",
    y="USD_Worldwide_Gross"
)

plt.figure(figsize=(8,4), dpi=200)
with sns.axes_style("whitegrid"):
  sns.regplot(data=old_films, 
            x='USD_Production_Budget', 
            y='USD_Worldwide_Gross',
            scatter_kws = {'alpha': 0.4},
            line_kws = {'color': 'black'})

plt.figure(figsize=(8, 4), dpi=200)
with sns.axes_style("darkgrid"):
  ax = sns.regplot(
      data=new_films,
      x='USD_Production_Budget', 
      y='USD_Worldwide_Gross',
      scatter_kws = {'alpha': 0.3},
      line_kws = {'color': '#ff7c43'}
  )

  ax.set(ylim=(0, new_films['USD_Worldwide_Gross'].max()),
         xlim=(0, new_films['USD_Production_Budget'].max()), 
         ylabel="Revenue in $ Billions",
         xlabel="Budget in $100 millions"
  )
  

plt.show()

regression = LinearRegression()

# Explanatory Variable(s) or Feature(s)
X = pd.DataFrame(new_films, columns=['USD_Production_Budget'])
 
# Response Variable or Target
y = pd.DataFrame(new_films, columns=['USD_Worldwide_Gross'])

regression.fit(X, y)

regression.score(X, y)

X = pd.DataFrame(old_films, columns=['USD_Production_Budget'])

y = pd.DataFrame(old_films, columns=['USD_Worldwirde_Gross'])

regression.fit(X, y)

